; Generated by tools/generate.ps1 from config/bindings.json. Do not edit.
;   chord set: f13

BINDINGS_SOURCE_HASH := "A3E398D18DE0AEF7EC14645C36FC9833AA61866E925CC3A876266A63577CA425"

TIMING := Map(
    "doubleTapMs",       400,
    "holdMs",            400,
    "modifierReleaseMs", 300)

RELAY := Map(
    "runHidden", true,
    "logFile",   "logs\relay.log")

SCREENSHOT := Map(
    "saveDir", "")

BINDINGS := Map(
    "^!+F13", Map(
        "id",      "taskView",
        "label",   "Task View",
        "base",    "F13",
        "display", "Ctrl + Alt + Shift + F13",
        "mode",    "tapDouble",
        "primary", Map(
            "action",  "scaffold",
            "slot",    "vite-react-ts",
            "label",   "Vite + React + TypeScript",
            "gesture", "single tap",
            "script",  "scaffolds\vite-react-ts.ps1"),
        "secondary", Map(
            "action",  "scaffold",
            "slot",    "nextjs",
            "label",   "Next.js",
            "gesture", "double tap",
            "script",  "scaffolds\nextjs.ps1")
    ),
    "^!+F14", Map(
        "id",      "undo",
        "label",   "Undo",
        "base",    "F14",
        "display", "Ctrl + Alt + Shift + F14",
        "mode",    "tapDouble",
        "primary", Map(
            "action",  "scaffold",
            "slot",    "sveltekit",
            "label",   "SvelteKit",
            "gesture", "single tap",
            "script",  "scaffolds\sveltekit.ps1"),
        "secondary", Map(
            "action",  "scaffold",
            "slot",    "astro",
            "label",   "Astro",
            "gesture", "double tap",
            "script",  "scaffolds\astro.ps1")
    ),
    "^!+F15", Map(
        "id",      "screenshot",
        "label",   "Screenshot",
        "base",    "F15",
        "display", "Ctrl + Alt + Shift + F15",
        "mode",    "tapHold",
        "primary", Map(
            "action",  "captureScreen",
            "slot",    "",
            "label",   "Full-screen capture to clipboard",
            "gesture", "quick tap",
            "script",  "capture\capture-fullscreen.ps1"),
        "secondary", Map(
            "action",  "snipRecord",
            "slot",    "",
            "label",   "Start/stop screen recording (Win+Shift+R)",
            "gesture", "hold >= 400ms",
            "script",  "")
    )
)
